bot_user_id = '@twim:cadair.com'
reporting_room_id = '!QQpfJfZvqxbCfeDgCj:matrix.org'
admin_room_id = '!yHqAuTnFgksYvVnlMY:ergaster.org'
notice_emoji = 'â­•ï¸'
image_emoji = 'ğŸ“·ï¸'
image_markdown = '> ![](/blog/img/{{file}})'
video_emoji = 'ğŸ“¹ï¸'
video_markdown = '> {{< video src="{{file}}" >}}'
update_config_command = "sh /data/update_config.sh"
editors = [
    '@thib:ergaster.org'
]

[[sections]]
emoji = 'âœ…'
name = 'todo'
title = 'TODO UNKNOWN SECTION'
order = 100
usual_reporters = []

[[sections]]
emoji = 'ğŸŒ¡ï¸'
name = 'status'
title = 'Dept of *Status of Matrix* ğŸŒ¡ï¸'
order = 200
usual_reporters = []

[[sections]]
emoji = 'ğŸ™†'
name = 'social'
title = 'Dept of Social Good ğŸ™†'
order = 250
usual_reporters = ['@denise.a:vector.modular.im']

[[sections]]
emoji = 'ğŸ“œ'
name = 'spec'
title = 'Dept of Spec ğŸ“œ'
order = 300
usual_reporters = ['@andrewm:amorgan.xyz']

[[sections]]
emoji = 'ğŸ“ï¸'
name = 'gsoc'
title = 'Dept of GSoC ğŸ“ï¸'
order = 400
usual_reporters = []

[[sections]]
emoji = 'ğŸ‘¥'
name = 'p2p'
title = 'Dept of P2P ğŸ‘¥'
order = 600
usual_reporters = []

[[sections]]
emoji = 'ğŸ¢'
name = 'servers'
title = 'Dept of Servers ğŸ¢'
order = 700
usual_reporters = []

[[sections]]
emoji = 'ğŸ“¥ï¸'
name = 'homeserver-deployment'
title = 'Homeserver Deployment ğŸ“¥ï¸'
order = 800
usual_reporters = []

[[sections]]
emoji = 'ğŸŒ‰'
name = 'bridges'
title = 'Dept of Bridges ğŸŒ‰'
order = 900
usual_reporters = []

[[sections]]
emoji = 'ğŸ“±'
name = 'clients'
title = 'Dept of Clients ğŸ“±'
order = 1000
usual_reporters = []

[[sections]]
emoji = 'ğŸ›ï¸'
name = 'non-chat-clients'
title = 'Dept of Non Clients ğŸ›ï¸'
order = 1020
usual_reporters = []

[[sections]]
emoji = 'ğŸ¤™'
name = 'voip'
title = 'Dept of VoIP ğŸ¤™'
order = 1050
usual_reporters = []

[[sections]]
emoji = 'ğŸ”'
name = 'encryption'
title = 'Dept of Encryption ğŸ”'
order = 1100
usual_reporters = []

[[sections]]
emoji = 'ğŸ§°'
name = 'sdks'
title = 'Dept of SDKs and Frameworks ğŸ§°'
order = 1200
usual_reporters = []

[[sections]]
emoji = 'ğŸ› ï¸'
name = 'ops'
title = 'Dept of Ops ğŸ› '
order = 1300
usual_reporters = []

[[sections]]
emoji = 'ğŸš€'
name = 'services'
title = 'Dept of Services ğŸš€'
order = 1400
usual_reporters = []

[[sections]]
emoji = 'ğŸ¤·'
name = 'blockchain'
title = 'Dept of Blockchain ğŸ¤·'
order = 1500
usual_reporters = []

[[sections]]
emoji = 'ğŸ’¡'
name = 'iot'
title = 'Dept of Internet of Things ğŸ’¡'
order = 1600
usual_reporters = []

[[sections]]
emoji = 'ğŸ¤–'
name = 'bots'
title = 'Dept of Bots ğŸ¤–'
order = 1700
usual_reporters = []

[[sections]]
emoji = 'ğŸ“¹'
name = 'eventvideos'
title = 'Dept of Event Videos ğŸ“¹'
order = 1800
usual_reporters = []

[[sections]]
emoji = 'ğŸ—£ï¸'
name = 'talks'
title = 'Dept of Events and Talks ğŸ—£ï¸'
order = 1900
usual_reporters = []

[[sections]]
emoji = 'ğŸ›°ï¸'
name = 'projects'
title = 'Dept of Interesting Projects ğŸ›°ï¸'
order = 2000
usual_reporters = []

[[sections]]
emoji = 'ğŸ—ï¸'
name = 'build'
title = 'Dept of *Built on Matrix* ğŸ—ï¸'
order = 2050
usual_reporters = []

[[sections]]
emoji = 'ğŸ§­'
name = 'guides'
title = 'Dept of Guides ğŸ§­'
order = 2100
usual_reporters = []

[[sections]]
emoji = 'ğŸ•'
name = 'hackathons'
title = 'Dept of Hackathons ğŸ•'
order = 2200
usual_reporters = []

[[sections]]
emoji = 'ğŸ’°ï¸'
name = 'jobs'
title = 'Dept of Jobs ğŸ’°ï¸'
order = 2300
usual_reporters = []

[[sections]]
emoji = 'ğŸ“°'
name = 'news'
title = 'Matrix in the News ğŸ“°'
order = 2400
usual_reporters = []

[[sections]]
emoji = 'ğŸŸï¸'
name = 'rooms'
title = 'New Public Rooms ğŸŸï¸'
order = 2500
usual_reporters = []

[[sections]]
emoji = 'ğŸ‘'
name = 'welcome'
title = 'Dept of Welcomes ğŸ‘'
order = 3000
usual_reporters = []

[[sections]]
emoji = 'ğŸ“†'
name = 'room-of-the-week'
title = 'Room of the Week ğŸ“†'
order = 3600
usual_reporters = ['@timokoesters:fachschaften.org']

[[sections]]
emoji = 'ğŸ’­'
name = 'thoughts'
title = 'Final Thoughts ğŸ’­'
order = 4000
usual_reporters = []

[[projects]]
emoji = 'Nheko?'
name = 'nheko'
title = 'Nheko'
description = 'Desktop client for Matrix using Qt and C++17.'
website = 'https://nheko-reborn.github.io'
default_section = 'clients'
usual_reporters = ['@deepbluev7:neko.dev']

[[projects]]
emoji = 'Fractal?'
name = 'fractal'
title = 'Fractal'
description = 'Matrix messaging app for GNOME written in Rust.'
website = 'https://gitlab.gnome.org/GNOME/fractal'
default_section = 'clients'
usual_reporters = ['@afranke:matrix.org']

[[projects]]
emoji = 'FluffyChat?'
name = 'fluffychat'
title = 'FluffyChat'
description = ''
website = 'https://fluffychat.im'
default_section = 'clients'
usual_reporters = [
    '@krille:janian.de',
    '@Sorunome:matrix.org'
]

[[projects]]
emoji = 'Synapse?'
name = 'synapse'
title = 'Synapse'
description = 'Synapse is the reference homeserver for Matrix'
website = 'https://github.com/matrix-org/synapse/'
default_section = 'servers'
usual_reporters = [
    '@callahad:matrix.org',
    '@erikj:jki.re',
    '@babolivier:vector.modular.im',
    '@dmrobertson:matrix.org'
]

[[projects]]
emoji = 'Hydrogen?'
name = 'hydrogen'
title = 'Hydrogen'
description = 'Hydrogen is a lightweight matrix client with legacy and mobile browser support'
website = 'https://github.com/vector-im/hydrogen-web'
default_section = 'clients'
usual_reporters = ['@bwindels:matrix.org']

[[projects]]
emoji = 'Heisenbridge?'
name = 'heisenbridge'
title = 'Heisenbridge'
description = 'Heisenbridge is a bouncer-style Matrix IRC bridge.'
website = 'https://github.com/hifi/heisenbridge/'
default_section = 'bridges'
usual_reporters = ['@hifi:vi.fi']

[[projects]]
emoji = 'GoMatrixHosting?'
name = 'gomatrixhosting'
title = 'GoMatrixHosting'
description = 'GoMatrixHosting deploys Matrix, Element and Jitsti instance as managed services'
website = 'http://gomatrixhosting.com'
default_section = 'services'
usual_reporters = ['@michael:perthchat.org']

[[projects]]
emoji = 'Cinny?'
name = 'cinny'
title = 'Cinny'
description = 'Cinny is a Matrix client focused on simplicity, elegance and security'
website = 'https://cinny.in'
default_section = 'clients'
usual_reporters = [
    '@ajbura:matrix.org',
    '@kfiven:matrix.org'
]

[[projects]]
emoji = 'Quaternion?'
name = 'quaternion'
title = 'Quaternion'
description = 'A Qt5-based IM client for Matrix'
website = 'https://github.com/quotient-im/Quaternion'
default_section = 'clients'
usual_reporters = ['@kitsune:matrix.org']

[[projects]]
emoji = 'libQuotient?'
name = 'libquotient'
title = 'libQuotient'
description = 'A Qt5 library to write cross-platform clients for Matrix'
website = 'https://github.com/quotient-im/libQuotient'
default_section = 'sdks'
usual_reporters = ['@kitsune:matrix.org']

[[projects]]
emoji = 'Conduit?'
name = 'conduit'
title = 'Conduit'
description = 'Conduit is a simple, fast and reliable chat server powered by Matrix'
website = 'https://conduit.rs'
default_section = 'servers'
usual_reporters = ['@timokoesters:fachschaften.org']

[[projects]]
emoji = 'Element?'
name = 'element'
title = 'Element'
description = 'Everything related to Element but not strictly bound to a client'
website = 'https://element.io'
default_section = 'clients'
usual_reporters = [
    '@thib:ergaster.org',
    '@kittykat:matrix.org',
    '@valere35:matrix.org',
    '@nadonomy:matrix.org',
    '@jsalter:matrix.org',
    '@daniellekirkwood:matrix.org'
]

[[projects]]
emoji = 'Emt Web?'
name = 'element-web'
title = 'Element Web/Desktop'
description = 'Secure and independent communication, connected via Matrix. Come talk with us in [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org)!'
website = 'https://github.com/vector-im/element-web'
default_section = 'clients'
usual_reporters = [
	'@thib:ergaster.org',
    '@kittykat:matrix.org'
]

[[projects]]
emoji = 'Emt iOS?'
name = 'element-ios'
title = 'Element iOS'
description = 'Secure and independent communication for iOS, connected via Matrix. Come talk with us in [#element-ios:matrix.org](https://matrix.to/#/#element-ios:matrix.org)!'
website = 'https://github.com/vector-im/element-ios'
default_section = 'clients'
usual_reporters = [
    '@thib:ergaster.org',
    '@kittykat:matrix.org'
]

[[projects]]
emoji = 'Emt Android?'
name = 'element-android'
title = 'Element Android'
description = 'Secure and independent communication for Android, connected via Matrix. Come talk with us in [#element-android:matrix.org](https://matrix.to/#/#element-android:matrix.org)!'
website = 'https://github.com/vector-im/element-android'
default_section = 'clients'
usual_reporters = [
    '@thib:ergaster.org',
    '@kittykat:matrix.org',
    '@benoit.marty:matrix.org'
]

[[projects]]
emoji = 'NeoChat?'
name = 'neochat'
title = 'Neochat'
description = 'A client for matrix, the decentralized communication protocol'
website = 'https://invent.kde.org/network/neochat'
default_section = 'clients'
usual_reporters = [
    '@tobiasfella:kde.org',
    '@carl:kde.org'
]

[[projects]]
emoji = 'Dendrite?'
name = 'dendrite'
title = 'Dendrite'
description = 'Second generation Matrix homeserver'
website = 'https://invent.kde.org/network/neochat'
default_section = 'servers'
usual_reporters = [
    '@neilalexander:matrix.org',
    '@neilalexander:dendrite.matrix.org'
]

[[projects]]
emoji = 'Slack Bridge?'
name = 'slack-bridge'
title = 'Slack Bridge'
description = 'A Matrix <-> Slack bridge'
website = 'https://github.com/matrix-org/matrix-appservice-slack'
default_section = 'bridges'
usual_reporters = ['@Half-Shot:half-shot.uk']

[[projects]]
emoji = 'Helm Chart?'
name = 'helm-chart'
title = 'Helm Chart'
description = 'Matrix Kubernetes applications packaged into helm charts'
website = 'https://gitlab.com/ananace/charts'
default_section = 'homeserver-deployment'
usual_reporters = ['@ace:kittenface.studio']

[[projects]]
emoji = 'Pinecone?'
name = 'pinecone'
title = 'Pinecone'
description = 'Peer-to-peer overlay routing for the Matrix ecosystem'
website = 'https://github.com/matrix-org/pinecone'
default_section = 'p2p'
usual_reporters = [
    '@neilalexander:matrix.org',
    '@neilalexander:dendrite.matrix.org'
]

[[projects]]
emoji = 'Halcyon?'
name = 'halcyon'
title = 'Halcyon'
description = 'Halcyon is an easy to use matrix library inspired by discord.py'
website = 'https://github.com/WesR/Halcyon'
default_section = 'sdks'
usual_reporters = ['@gen3:blackline.xyz']

[[projects]]
emoji = 'SchildiChat?'
name = 'schildichat'
title = 'SchildiChat'
description = 'SchildiChat is a fork of Element that focuses on UI changes such as message bubbles and a unified chat list for both direct messages and groups, which is a more familiar approach to users of other popular instant messengers.'
website = 'https://schildi.chat'
default_section = 'clients'
usual_reporters = ['@qg:supercable.onl']

[[projects]]
emoji = 'standupbot?'
name = 'standupbot'
title = 'standupbot'
description = 'Standupbot helps automate the process of writing nicely formatted daily standup posts and sending that standup post to a shared, configurable standup room.'
website = 'https://sr.ht/~sumner/standupbot/'
default_section = 'bots'
usual_reporters = ['@sumner:sumnerevans.com']

[[projects]]
emoji = 'PTSN Bridge?'
name = 'ptsn-bridge'
title = 'PTSN Bridge'
description = 'A matrix <-> SIP bridge'
website = 'https://github.com/alangecker/matrix-appservice-pstn'
default_section = 'bridges'
usual_reporters = ['@chandi:livingutopia.org']

[[projects]]
emoji = 'Mother Miounne?'
name = 'mother-miounne'
title = 'Mother Miounne'
description = 'The backoffice of etke.cc service'
website = 'https://gitlab.com/etke.cc/miounne'
default_section = 'ops'
usual_reporters = ['@aine:etke.cc']

[[projects]]
emoji = 'etke.cc?'
name = 'etke'
title = 'etke.cc'
description = 'Your matrix server on your conditions'
website = 'https://etke.cc'
default_section = 'services'
usual_reporters = ['@aine:etke.cc']

[[projects]]
emoji = 'Review Bot?'
name = 'matrix-review-bot'
title = 'matrix-review-bot'
description = 'Get your latest AppStore & Playstore review directly in your fav matrix room.'
website = 'https://github.com/BillCarsonFr/matrix-review-bot'
default_section = 'bots'
usual_reporters = ['@valere35:matrix.org']

[[projects]]
emoji = 'Collabs?'
name = 'collabs'
title = 'Collabs'
description = 'A library to make decentralized collaborative apps'
website = 'https://www.npmjs.com/package/@collabs/collabs'
default_section = 'sdks'
usual_reporters = ['@mweidner:matrix.org']

[[projects]]
emoji = 'MRSBFH?'
name = 'mrsbfh'
title = 'Matrix-Rust-SDK-Bot-Framework-Helper'
description = 'A toolkit for writing commandbots more efficient in rust for matrix.'
website = 'https://github.com/MTRNord/mrsbfh'
default_section = 'sdks'
usual_reporters = ['@mtrnord:nordgedanken.dev']

[[projects]]
emoji = 'mautrix-whatsapp?'
name = 'mautrix-whatsapp'
title = 'mautrix-whatsapp'
description = 'A Matrix-WhatsApp puppeting bridge'
website = 'https://github.com/mautrix/whatsapp'
default_section = 'bridges'
usual_reporters = ['@tulir:maunium.net']

[[projects]]
emoji = 'simplematrixbotlib?'
name = 'simplematrixbotlib'
title = 'simplematrixbotlib'
description = 'simplematrixbotlib is an easy to use bot library for the Matrix ecosystem written in Python and based on matrix-nio.'
website = 'https://github.com/KrazyKirby99999/simple-matrix-bot-lib'
default_section = 'sdks'
usual_reporters = ['@krazykirby99999:matrix.org']

[[projects]]
emoji = 'time-to-matrix?'
name = 'time-to-matrix'
title = 'time-to-matrix'
description = 'The time command, but it sends the output to a Matrix room'
website = 'https://gitlab.com/etke.cc/ttm'
default_section = 'non-chat-clients'
usual_reporters = ['@aine:etke.cc']

[[projects]]
emoji = 'Mjolnir?'
name = 'mjolnir'
title = 'MjÃ¶lnir'
description = 'The moderation bot for Matrix'
website = 'https://github.com/matrix-org/mjolnir'
default_section = 'bots'
usual_reporters = ['@dotyoric:matrix.org']

[[projects]]
emoji = 'synadm?'
name = 'synadm'
title = 'synadm'
description = 'Command line admin tool for Synapse (Matrix reference homeserver)'
website = 'https://github.com/JOJ0/synadm'
default_section = 'ops'
usual_reporters = ['@jojo:peek-a-boo.at']

[[projects]]
emoji = 'jOlm?'
name = 'jolm'
title = 'jOlm'
description = 'Olm bindings for Java'
website = 'https://github.com/brevilo/jolm'
default_section = 'sdks'
usual_reporters = ['@brevilo:matrix.org']

[[projects]]
emoji = 'MinesTRIX?'
name = 'minestrix'
title = 'MinesTRIX'
description = 'A privacy focused social media based on MATRIX'
website = 'https://minestrix.henri2h.fr'
default_section = 'projects'
usual_reporters = ['@henri2h:carnot.cc']

[[projects]]
emoji = 'hookshot?'
name = 'matrix-hookshot'
title = 'matrix-hookshot'
description = 'A multi purpose multi platform bridge, formerly known as matrix-github'
website = 'https://github.com/Half-Shot/matrix-hookshot'
default_section = 'bridges'
usual_reporters = ['@Half-Shot:half-shot.uk']
